hibernate.connection.driver_class =com.mysql.cj.jdbc.Driver
hibernate.connection.url =jdbc:mysql://localhost:3306/serenity_therapy_center?createDatabaseIfNotExist=true
hibernate.connection.username =root
hibernate.connection.password =mysql
hibernate.dialect =org.hibernate.dialect.MySQLDialect
hibernate.hbm2ddl.auto =update
hibernate.show_sql =true
hibernate.format_sql =true
hibernate.current_session_context_class =thread


## Enable Hibernate statistics (optional, but useful for monitoring cache performance)
hibernate.generate_statistics =true

# Enable Second Level Cache
hibernate.cache.use_second_level_cache=true

# Enable Query Cache (optional, for HQL/JPQL queries)
hibernate.cache.use_query_cache=true

# Define Cache Region Factory (Using JCache/Ehcache 3)
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory

# Provider class for Ehcache 3
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider





